version: 2.1

orbs:
  rust: circleci/rust@1.6.0
  node: circleci/node@5.0.0
  win: circleci/windows@2.2.0


jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - node/install-packages


workflows:
  ci-workflow:
    jobs:
      - build
